### ISSUE TITLE
Sort button behavior not following the DisplaySortButtons parameter

### ISSUE THREAD

**Issue by Re-nard** [Goldenrevolver/QuickStackStore#10]
Hi Golden,

I just noticed a light bug in the behavior of the sort button.
As for the restock and quick stack buttons, I set the 'DisplaySortButtons' parameter to 'BothButDependingOnContext' so that when I open a container, the three little buttons disappear while it is opened. It is working fine for the restock and quick stack ones, but not for the sort button. When I open a container, it stays displayed. Once, I even got it undisplayed even with no container opened.

Here are some screenshots :
![image](https://user-images.githubusercontent.com/123848483/225191771-2a59a412-fc3f-4b30-838b-43a25e6bd81a.png)

With container opened :
![image](https://user-images.githubusercontent.com/123848483/225191807-0b7f9d7b-18bb-40f8-a969-15e102ff9140.png)

the config :
![image](https://user-images.githubusercontent.com/123848483/225192327-9eec9c4d-70d2-44c4-94d3-31bd792954fe.png)

On the screenshots I have the azu extended inventory mod activated, but I tried on a test game with only last version of bepinex and your mod and the bug was still there.

I can provide more details if you need so.
Anyway, your mods are great, thanks a lot for your work and have a nice day 😄

**Comment by Goldenrevolver** [comment]
the actual bug is that BothButDependingOnContext is even an option for the sort button. because I originally wanted the inventory sort button to always be visible. but I guess, now that I accidentally added it, I can change the code to hide the inventory sort button when the chest sort button is shown

thanks for the report

**Comment by Re-nard** [comment]
Thank you for your answer Golden !
And thanks for your work, have a great day !

**Comment by Goldenrevolver** [comment]
actually I misremembered. it is a bug. I had the code written already, but it didn't work. it's fixed in 1.3.11 soon

**Comment by Goldenrevolver** [comment]
fixed in 1.4.0
