### ISSUE TITLE
QuickStack exception on latest update (v0.216.9); 

### ISSUE THREAD

**Issue by Lopeh** [Goldenrevolver/QuickStackStore#13]
Quick summary: Using QuickStack without a container open doesn't appear to do anything. 

Game Version: v0.216.9
Game state: Local w/out dedicated server

Mods: 
BepInEx: [v5.4.2105](https://valheim.thunderstore.io/package/denikson/BepInExPack_Valheim/5.4.2105/)
BepInEx Configuration Manager: [v18.0.0](https://valheim.thunderstore.io/package/Azumatt/Official_BepInEx_ConfigurationManager/18.0.0/)
Quick Stack Store: [v1.3.10](https://valheim.thunderstore.io/package/Goldenrevolver/Quick_Stack_Store_Sort_Trash_Restock/1.3.10/)

Debug steps:
* Ran game in Vanilla state, saved. Re-loaded with select mods above.
* All settings default/fresh install
* Changed default keybind from P to BackQuote
* Changed QuickStackTrophiesIntoSameContainer to Enabled

Full Summary:
Clicking the Quickstack icon without a container open, or using the shortcut doesn't do anything. When checking the Console log, the following error is displayed using the shortcut:

```
[Error  : Unity Log] MissingMethodException: long ZNet.GetUID()
Stack trace:
QuickStackStore.QuickStackModule.QuickStackIntoMultipleContainers (System.Collections.Generic.List`1[T] trophies, System.Collections.Generic.List`1[T] nonTrophies, Player player, System.Collections.Generic.List`1[T] containers) (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
QuickStackStore.QuickStackModule.DoQuickStack (Player player, System.Boolean QuickStackOnlyToCurrentContainerOverride) (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
QuickStackStore.KeybindChecker+Player_Update_Patch.HandleGenericKeys (Player player) (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
QuickStackStore.KeybindChecker+Player_Update_Patch.Postfix_Patch (Player __instance) (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)
```

The following error displayed when using the Q button from the inventory window:

```
[Error  : Unity Log] MissingMethodException: long ZNet.GetUID()
Stack trace:
QuickStackStore.QuickStackModule.QuickStackIntoMultipleContainers (System.Collections.Generic.List`1[T] trophies, System.Collections.Generic.List`1[T] nonTrophies, Player player, System.Collections.Generic.List`1[T] containers) (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
QuickStackStore.QuickStackModule.DoQuickStack (Player player, System.Boolean QuickStackOnlyToCurrentContainerOverride) (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
QuickStackStore.ButtonRenderer+MainButtonUpdate+<>c.<UpdateInventoryGuiButtons>b__0_6 () (at <7038b2bb98ca4ab0b7829a4bfa31c245>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <80fe1a4e36fe44618284312cb721a597>:0)
UnityEngine.UI.Button.Press () (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <e97aac8d17514bea83fadfd039e9187a>:0)
UnityEngine.EventSystems.EventSystem:Update()
```

**Comment by joviancw** [comment]
I ran into this too on the latest build.

**Comment by Lopeh** [comment]
It's worth noting even the original [Quick Stack](https://valheim.thunderstore.io/package/damnsneaker/QuickStack/) mod is getting a similar bug.

**Comment by kadamczy** [comment]
I have this fixed for everything but the trash button in the UI. If I can get that fixed I'll do a pull request to incorporate the changes. 

It's all just because they changed the method names for a ton of things (and how to get a UID)

**Comment by Goldenrevolver** [comment]
did the update fix all these issues?
