### ISSUE TITLE
Quick sort and restack buttons missing from inventory UI 

### ISSUE THREAD

**Issue by CrumpThePenguin** [Goldenrevolver/QuickStackStore#3]
As of the recent update 1.3.1 the aforementioned buttons are missing from the inventory UI. The "Sort" button is still there but none of the others. Sorting still works using hotkeys though.

**Comment by CrumpThePenguin** [comment]
Fixed by having server host enable the config setting "AllowAreaStackingInMultiplayerWithoutMUC". Not sure if this is a new feature with update or if something broke, but this seems to resolve it.

**Comment by FoxMcloud5655** [comment]
Noted.  Thank you for the follow-up.
