### ISSUE TITLE
quickstackstore mod...currently on my dedicated server

### ISSUE THREAD

**Issue by hsdisciple** [Goldenrevolver/QuickStackStore#5]
at the moment on the dedicated server I am up able to use quickstack to any chest whether its the "Q" button or the hotkey. I dont see any problems in the log output.
[LogOutput.log](https://github.com/Goldenrevolver/QuickStackStore/files/10563386/LogOutput.log)

**Comment by Goldenrevolver** [comment]
did you read the changelog or the nexus sticky note about the new config setting "AllowAreaStackingInMultiplayerWithoutMUC"?
